stickies/urls.py
from django.conf.urls.defaults import *
import os
from settings import PROJECT_ROOT

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^stickies/', include('stickies.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),
    (r'^$', 'notes.views.index'),
    (r'^project/(?P<id>[0-9]+)/$', 'notes.views.project'),
    (r'^ajax/', 'notes.views.ajax'),
    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': os.path.join(PROJECT_ROOT, 'media')}),
    
    (r'accounts/login/$', 'django.contrib.auth.views.login'),
    (r'accounts/logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/'}),
)

stickies/notes/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save


note_states = (
    ('todo', 'To Do',),
    ('inprogress', 'In Progress',),
    ('document', 'Document',),
    ('test', 'Test',),
    ('verify', 'Verify',),
    ('done', 'Done',),
)

class UserProfile(models.Model):
    user = models.OneToOneField(User, primary_key=True)

    def __unicode__(self):
        return self.user.username

class Project(models.Model):
    name = models.CharField(max_length=250)
    active = models.BooleanField(default=True)
    group = models.ForeignKey(Group, null=True, blank=True)

    def save(self, *args, **kwds):
        g = Group.objects.create(name=self.name)
        self.group = g
        return super(Project, self).save(args, kwds)

    def __unicode__(self):
        return self.name


class Note(models.Model):
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, related_name='authors')
    project = models.ForeignKey(Project)
    last_changed_by = models.ForeignKey(User, null=True, blank=True)
    state = models.CharField(choices=note_states, max_length=13,
        default='todo')

    def save(self, *args, **kwds):
        if not self.last_changed_by:
            self.last_changed_by = self.author
        super(Note, self).save(args, kwds)

    def __unicode__(self):
        return self.content


def create_profile(sender, **kw):
    user = kw["instance"]
    if kw["created"]:
        profile = UserProfile(user=user)
        profile.save()

post_save.connect(create_profile, sender=User)

stickies/notes/views.py
from django.http import HttpResponse, Http404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from models import Note, Project
from django.shortcuts import render_to_response, get_object_or_404
import simplejson as json


STATES = ['todo', 'inprogress', 'document', 'test', 'verify', 'done']


def index(request):
    if request.user.is_authenticated():
        projects = Project.objects.all()
    else:
        projects = None
    return render_to_response('index.html', {'projects': projects},
            context_instance=RequestContext(request))

@login_required
def project(request, id):
    project = Project.objects.get(id=id)
    group = get_object_or_404(Group, name=project.name)
    if group not in request.user.groups.all():
        raise Http404
    return render_to_response('project.html', {'project': project})

@login_required
def ajax(request):
    r = _ajax(request)
    return HttpResponse(json.dumps(r))

def _ajax(request):
    """Wrapper"""
    if not request.is_ajax():
        return {'status': 403}
        
    a = request.POST.get('a')
    if a not in ['move', 'edit', 'delete', 'new']:
        return {'status': 403}
    
    if a in ['move', 'edit', 'delete']:
        n = request.POST.get('note')
        id = int(n[5:])
        note = get_object_or_404(Note, pk=id)
        try:
            note = Note.objects.get(pk=id)
        except ObjectDoesNotExist:
            return {'status': 403}

    if a in ['edit', 'new']:
        content = request.POST.get('content')

    if a == 'move':
        st = request.POST.get('section')
        if st not in STATES:
            return {'status': 403}
        note.state = st
    elif a == 'delete':
        note.delete()
        return {'status': 200}
    elif a == 'new':
        p = request.POST.get('project')
        p = get_object_or_404(Project, id=p)
        note = Note(
            content=content,
            author=request.user,
            project=p)
        note.save()
        return {
            'status': 200,
            'content': _note(note)
        }
    else:
        note.content = content
    note.save()
    return {'status': 200}

def _note(note):
    t = """
<div id="note-%d" class="portlet ui-widget ui-widget-content ui-helper-clearfix ui-corner-all"><div class="portlet-header ui-widget-header ui-corner-all"><span class="ui-icon ui-icon-close"></span><span class="ui-icon ui-icon-pencil"></span></div>
    <div class="portlet-content">%s</div>
    <div class="portlet-meta">
        <p>Author: %s</p>
    </div>
</div>
"""
    n = t % (note.id, note.content, note.author.username,)
    return n

stickies/notes/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">

    <title>{% block title %}{% endblock %} - Stickies App</title>
    <link  href="//fonts.googleapis.com/css?family=Ubuntu:regular,italic,bold,bolditalic" rel="stylesheet" type="text/css" >
    <link href="/static/css/jquery-ui-1.8.7.custom.css" rel="stylesheet" type="text/css" media="screen" charset="utf-8">
    <link rel="stylesheet" href="/static/css/style.css" type="text/css" media="screen" charset="utf-8">
    <script src="/static/js/jquery-1.4.4.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="/static/js/jquery-ui-1.8.7.custom.min.js" type="text/javascript" charset="utf-8"></script>
    <script src="/static/notes.js" type="text/javascript" charset="utf-8"></script>
    
</head>
<body>

    {% block content %}

    {% endblock %}
</body>
</html>

stickies/notes/templates/index.html
{% extends "base.html" %}

{% block title %}Your Projects{% endblock %}

{% block content %}

<div id="home">
<h1>StickiesApp</h1>

{% if user.is_authenticated %}
    <h2>Your Projects</h2>
    {% if projects %}
        {% for project in projects %}
            <a href="/project/{{ project.id }}/">{{ project.name }}</a><br>
        {% endfor %}
    {% else %}
        <p>You have no projects</p>
    {% endif %}

    <div id="footer">
        <a href="/accounts/logout/">Log out</a>
    </div>
{% else %}
    <a href="/accounts/login/">Log in</a>
{% endif %}

</div>
{% endblock %}

stickies/notes/templates/project.html
{% extends "base.html" %}

{% block title %}Your Projects{% endblock %}

{% block content %}

<script type="text/javascript" charset="utf-8">
    var _project = {{ project.id }};
</script>

<span id="logo">StickiesApp</span>
 - Current Project: <span id="project-title">{{ project.name }}</span>
 - <a href="/">Home</a>
 - <a href="#" id="new-sticky">New Sticky</a>

<div id="main">
    <ul id="column-labels">
        <li><h2>To Do</h2></li>
        <li><h2>In Progress</h2></li>
        <li><h2>Document</h2></li>
        <li><h2>Test</h2></li>
        <li><h2>Verify</h2></li>
        <li><h2>Done</h2></li>
    </ul>

    <div id="todo" class="column">
        {% for note in project.note_set.all %}
            {% if note.state == 'todo' %}
            <div id="note-{{ note.id }}" class="portlet ui-widget">
                <div class="portlet-content">{{ note.content }}</div>
                <div class="portlet-meta">
                    <p>Author: {{ note.author.username }}</p>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>

    <div id="inprogress" class="column">
        {% for note in project.note_set.all %}
            {% if note.state == 'inprogress' %}
            <div id="note-{{ note.id }}" class="portlet">
                <div class="portlet-content">{{ note.content }}</div>
                <div class="portlet-meta">
                    <p>Author: {{ note.author.username }}</p>
                </div>
            </div>
            {% endif %}
        {% endfor %}

    </div>

    <div id="document" class="column">
        {% for note in project.note_set.all %}
            {% if note.state == 'document' %}
            <div id="note-{{ note.id }}" class="portlet">
                <div class="portlet-content">{{ note.content }}</div>
                <div class="portlet-meta">
                    <p>Author: {{ note.author.username }}</p>
                </div>
            </div>
            {% endif %}
        {% endfor %}

    </div>

    <div id="test" class="column">
        {% for note in project.note_set.all %}
            {% if note.state == 'test' %}
            <div id="note-{{ note.id }}"  class="portlet">
                <div class="portlet-content">{{ note.content }}</div>
                <div class="portlet-meta">
                    <p>Author: {{ note.author.username }}</p>
                </div>
            </div>
            {% endif %}
        {% endfor %}

    </div>

    <div id="verify" class="column">
        {% for note in project.note_set.all %}
            {% if note.state == 'verify' %}
            <div id="note-{{ note.id }}"  class="portlet">
                <div class="portlet-content">{{ note.content }}</div>
                <div class="portlet-meta">
                    <p>Author: {{ note.author.username }}</p>
                </div>
            </div>
            {% endif %}
        {% endfor %}

    </div>

    <div id="done" class="column">
        {% for note in project.note_set.all %}
            {% if note.state == 'done' %}
            <div id="note-{{ note.id }}"  class="portlet">
                <div class="portlet-content">{{ note.content }}</div>
                <div class="portlet-meta">
                    <p>Author: {{ note.author.username }}</p>
                </div>
            </div>
            {% endif %}
        {% endfor %}

    </div>

</div>

<div id="dialog">
    <h3>Edit the sticky note:</h3>
    <textarea id="edit-sticky" cols="50" rows="5"></textarea>
</div>


{% endblock %}